name: Terminal Automation Test

on: [push, pull_request]

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: jq Kurulumu
        run: sudo apt-get install jq

      - name: Bash Scriptini Çalıştır
        run: |
          chmod +x api_health_check.sh
          ./api_health_check.sh